---
- name: Configure gnome-terminal
  tags: [gnome, gnome-terminal]
  block:
  - name: Import a default profile named "Sparkfabrik"
    command: "dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < {{ role_path }}/files/gnome-terminal-profile.dconf"
