---
- name: Install cloud native packages
  tags: [dev, cloudnative, packages]
  block:
    - name: Install cloud native packages
      community.general.pacman:
        name:
          - aws-cli
          - yq
          - jq
          - kubectl
          - helm
    - name: Install cloud native packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - pack-cli-bin
          - google-cloud-sdk
          - kind
          - kubectx
          - kubetail
          - rancher-k3d-bin
          - stern
          - tmate
      become: yes
      become_user: aur_builder
    - name: Install docker
      community.general.pacman:
        name:
          - docker
          - docker-compose
    - name: Add user paolo to docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
    - name: Enable docker service
      shell: systemctl enable docker

- name: Install base packages
  tags: [base, packages]
  block:
  - name: Install network packages
    community.general.pacman:
      name:
        - dnsutils
        - dhcpcd
        - iproute2
        - net-tools
        - tcpdump
        - wpa_supplicant

  - name: Install system packages
    community.general.pacman:
      name:
        - base-devel
        - bash-completion
        - dialog
        - dmidecode
        - flatpak
        - neofetch
        - pacman-contrib
        - gparted
        - htop
        - git
        - tree
        - usbutils
        - tmux
        - zsh
        - zsh-completions
        - lshw

  - name: Install system packages from aur
    kewlfft.aur.aur:
      use: paru
      name:
        - inxi
        - glxinfo
    become: yes
    become_user: aur_builder

  - name: Install base packages
    community.general.pacman:
      name:
        - deja-dup
        - guvcview
        - thefuck
        - yadm
        - vim
        - telegram-desktop
 
  - name: Install base packages from aur
    kewlfft.aur.aur:
      use: paru
      name:
        - toggldesktop
    become: yes
    become_user: aur_builder
        
  - name: Symlink vim to vi
    command: ln -sf /usr/bin/vim /usr/bin/vi

  - name: Install web browsers
    kewlfft.aur.aur:
      use: paru
      name:
        - google-chrome
        - firefox
    become: yes
    become_user: aur_builder

  - name: Install productivity packages from aur
    kewlfft.aur.aur:
      use: paru
      name:
        - slack-desktop
        - timeshift
        - timeshift-autosnap
        - visual-studio-code-bin
        - zoom
    become: yes
    become_user: aur_builder

- name: Install and configure fonts
  tags: [system, fonts]
  block:
  - name: Install fonts
    community.general.pacman:
      name:
        - fontconfig
        - adobe-source-sans-fonts
        - cantarell-fonts
        - noto-fonts
        - ttf-anonymous-pro
        - ttf-droid
        - ttf-liberation
        - ttf-fira-code
        - ttf-fira-mono
        - ttf-fira-sans
        - ttf-jetbrains-mono
        - ttf-lato
        - ttf-roboto
        - ttf-roboto-mono
        - ttf-ubuntu-font-family
        - ttf-ibm-plex
        - ttf-bitstream-vera
        - ttf-dejavu
        - ttf-hack
        - ttf-inconsolata
        - tamsyn-font
  - name: Enable rgb subpixel configuration
    file:
      src: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"
      dest: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
      state: link
  - name: Enable slight hinting
    file:
      src: "/usr/share/fontconfig/conf.avail/10-hinting-slight.conf"
      dest: "/etc/fonts/conf.d/10-hinting-slight.conf"
      state: link
  - name: Enable lcd filter
    file:
      src: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"
      dest: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
      state: link
  - name: Enable freetype2
    ansible.builtin.lineinfile:
      path: /etc/profile.d/freetype2.sh
      regexp: '^export FREETYPE_PROPERTIES='
      line: export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
  - name: Clear font cache
    command: fc-cache -fv

- name: Set up multimedia packages
  import_tasks: multimedia.yml
