---
- name: Productivity
  tags: [packages, productivity]
  block:
   - name: Ensure not installed
      kewlfft.aur.aur:
        name:
          - slack-desktop
        ensure: absent
      become: yes
      become_user: aur_builder
  
    - name: Install productivity packages
      community.general.pacman:
        name:
          - thefuck
          - yadm
          - gnupg
          - pinentry
          - telegram-desktop

    - name: Install productivity packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - slack-desktop
          - timeshift
          - visual-studio-code-bin
          - icu69-bin
          - zoom
          - xournalpp
      become: yes
      become_user: aur_builder

    - name: Install flatpak packages
      flatpak:
        name: 
          - com.slack.Slack
        state: present
