---
- name: Configure system components
  tags: [system, bluetooth]
  block:
    - name: Install bluetooth dependencies
      community.general.pacman:
        name:
          - blueman
          - bluez
          - bluez-utils

    - name: Activate bluetooth service
      command: systemctl enable bluetooth
